version: 0.2

phases:
  post_build:
    commands:
      - aws cloudfront create-invalidation \
        --distribution-id EHIWKYBD96BJ8 \
          --paths '/*'
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build


artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build